# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [50]:
'''
Your Code
'''
import numpy as np

a = np.random.randint(10, size=6)
b = np.random.randint(10, size=6).reshape(3,2)

print('list(a): ', list(a))
print('type: ', type(list(a)))
print('元素type: ', type(list(a)[0]))
print('-----------------------')
print('a.tolist(): ', a.tolist())
print('type: ', type(a.tolist()))
print('元素type: ', type(a.tolist()[0]))

print('=======================')
print(a)
print('list(a): ', list(a))
print('a.tolist', a.tolist())
print('-----------------------')
print(b)
print('list(b): ', list(b))
print('b.tolist', b.tolist())

list(a):  [4, 4, 0, 1, 1, 4]
type:  <class 'list'>
元素type:  <class 'numpy.int32'>
-----------------------
a.tolist():  [4, 4, 0, 1, 1, 4]
type:  <class 'list'>
元素type:  <class 'int'>
[4 4 0 1 1 4]
list(a):  [4, 4, 0, 1, 1, 4]
a.tolist [4, 4, 0, 1, 1, 4]
-----------------------
[[8 9]
 [4 9]
 [1 0]]
list(b):  [array([8, 9]), array([4, 9]), array([1, 0])]
b.tolist [[8, 9], [4, 9], [1, 0]]


list只將陣列中的第一個維度進行列表化(每個元素仍是陣列)；
tolist()將陣列中的數據全都列出(每個元素都是列表)

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```
```
ndim維度、shape形狀、size大小、dtype資料型態、
itemsize元素佔用空間、length元素長度、type物件型態
```

In [37]:
# 記得先 Import 正確的套件

'''
Your Code
'''
import numpy as np

a = np.random.randint(10, size=6) 

print('------array a-------')
print(a)

print('ndim: ', a.ndim)
print('shape: ', a.shape)
print('size: ', a.size)
print('dtype: ', a.dtype)
print('itemsize: ', a.itemsize)
print('length: ', len(a))
print('type: ', type(a))

------array a-------
[6 7 0 3 2 2]
ndim:  1
shape:  (6,)
size:  6
dtype:  int32
itemsize:  4
length:  6
type:  <class 'numpy.ndarray'>


In [40]:
b = np.random.randint(10, size=(3,4)) 

print('------array b-------')
print(b)

print('ndim: ', b.ndim)
print('shape: ', b.shape)
print('size: ', b.size)
print('dtype: ', b.dtype)
print('itemsize: ', b.itemsize)
print('length: ', len(b))
print('type: ', type(b))

------array b-------
[[2 0 6 4]
 [6 6 3 7]
 [4 4 8 5]]
ndim:  2
shape:  (3, 4)
size:  12
dtype:  int32
itemsize:  4
length:  3
type:  <class 'numpy.ndarray'>


In [43]:
c = np.random.randint(10, size=(2,3,2)) 

print('------array c-------')
print(c)

print('ndim: ', c.ndim)
print('shape: ', c.shape)
print('size: ', c.size)
print('dtype: ', c.dtype)
print('itemsize: ', c.itemsize)
print('length: ', len(c))
print('type: ', type(c))

------array c-------
[[[8 4]
  [5 9]
  [6 0]]

 [[4 4]
  [9 2]
  [9 2]]]
ndim:  3
shape:  (2, 3, 2)
size:  12
dtype:  int32
itemsize:  4
length:  2
type:  <class 'numpy.ndarray'>


In [ ]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''

[1 1 2 0 1 6]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [ ]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [51]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[6, 8, 0, 1, 8, 6]
[6, 8, 0, 1, 8, 6]


In [52]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[9, 7, 9, 2], [3, 7, 0, 1], [7, 8, 6, 1]]
[array([9, 7, 9, 2]), array([3, 7, 0, 1]), array([7, 8, 6, 1])]


In [53]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[1, 3], [7, 4], [8, 5]], [[5, 5], [0, 5], [9, 6]]]
[array([[1, 3],
       [7, 4],
       [8, 5]]), array([[5, 5],
       [0, 5],
       [9, 6]])]


In [54]:
#簡單版，使用遞迴迴圈將每一層往下解

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)
    '''
    Your Code
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 8, 0, 1, 8, 6]
[[9, 7, 9, 2], [3, 7, 0, 1], [7, 8, 6, 1]]
[[[1, 3], [7, 4], [8, 5]], [[5, 5], [0, 5], [9, 6]]]


In [56]:
#進階版

def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[6, 8, 0, 1, 8, 6]
[[9, 7, 9, 2], [3, 7, 0, 1], [7, 8, 6, 1]]
[[[1, 3], [7, 4], [8, 5]], [[5, 5], [0, 5], [9, 6]]]
